/*
 * action types
 */

// AUTH
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const HANDLE_MODAL_AUTH_STATE = 'HANDLE_MODAL_AUTH_STATE';
export const SET_URL_TO_REDIRECT_FROM_MODAL = 'SET_URL_TO_REDIRECT_FROM_MODAL';

// NEWS
export const SET_NEWS_LIST = 'SET_NEWS_LIST';
export const GET_NEWS_ITEM = 'GET_NEWS_ITEM';
export const EDIT_NEWS_ITEM = 'EDIT_NEWS_ITEM';
export const DELETE_NEWS_ITEM = 'DELETE_NEWS_ITEM';
export const NEWS_LIST_FETCH_DATA_SUCCESS = 'NEWS_LIST_FETCH_DATA_SUCCESS';
export const NEWS_LIST_FETCH_DATA_FAILURE = 'NEWS_LIST_FETCH_DATA_FAILURE';
export const NEWS_IS_LOADING = 'NEWS_IS_LOADING';










